# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  # clear_solid_queue_finished_jobs:
  #   command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
  #   schedule: every hour at minute 12

  sitemap_refresh:
    class: SitemapRefreshJob
    queue: default
    schedule: every week

  hub_cache_warm:
    class: HubCacheWarmJob
    queue: default
    schedule: every day at 4am

  # extract_pending_scores:
  #   class: ExtractPendingScoresJob
  #   queue: extractions
  #   args: [ { limit: 2500 } ]
  #   schedule: every 4 hours

  # generate_missing_thumbnails:
  #   class: GenerateMissingThumbnailsJob
  #   queue: default
  #   schedule: every day at 2am

  generate_missing_galleries:
    class: GenerateMissingGalleriesJob
    queue: default
    schedule: every day at 5am

  # sync_missing_pdfs:
  #   class: SyncMissingPdfsJob
  #   queue: default
  #   schedule: every day at 1am
